name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write  # ⚠️ 이 부분이 핵심

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: |
          mkdir -p data
          python scripts/fetch_data.py
          echo "생성된 파일:"
          ls -l data/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
