name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread google-auth
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Fetch Trucking Data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: |
          python scripts/fetch_truck_data.py
          echo "생성된 파일:"
          ls -la data/
          echo -e "\nJSON 내용 샘플:"
          jq '.["TN"]' data/us-truck.json || echo "JSON 파싱 실패"

      - name: Fetch Rail Data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: |
          python scripts/fetch_rail_data.py
          echo "Rail data file:"
          ls -la data/us-rail.json || echo "Rail data file not found"
          echo -e "\nRail data sample:"
          if [ -f "data/us-rail.json" ]; then
            jq '.[0]' data/us-rail.json
          else
            echo "No rail data file exists"
          fi

      - name: Fetch Ocean Data
        env:
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python scripts/fetch_ocean_data.py
          echo "Ocean data file:"
          ls -la data/us-ocean.json || echo "Ocean data file not found"
          echo -e "\nOcean data sample:"
          if [ -f "data/us-ocean.json" ]; then
            jq '.[0]' data/us-ocean.json
          else
            echo "No ocean data file exists"
          fi

      ---

      # 다음 스텝을 추가합니다: Fetch Air Data

      - name: Fetch Air Data
        env:
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }} # 만약 Air 데이터도 구글 시트를 사용한다면
        run: |
          python scripts/fetch_air_data.py
          echo "Air data file:"
          ls -la data/us-air.json || echo "Air data file not found"
          echo -e "\nAir data sample:"
          if [ -f "data/us-air.json" ]; then
            # air_map.js에서 사용하는 JSON 구조에 따라 적절한 샘플 출력으로 변경
            jq '.[0]' data/us-air.json
          else
            echo "No air data file exists"
          fi

      ---

      - name: Verify JSON files
        run: |
          echo "Trucking data sample:"
          if [ -f "data/us-truck.json" ]; then
            jq -r '.["TN"]' data/us-truck.json
          else
            echo "No truck data file exists"
          fi
          echo -e "\nRail data sample:"
          if [ -f "data/us-rail.json" ]; then
            jq -r '.[0]' data/us-rail.json
          else
            echo "No rail data file exists"
          fi
          echo -e "\nAir data sample:" # Air 데이터 샘플 검증 추가
          if [ -f "data/us-air.json" ]; then
            jq -r '.[0]' data/us-air.json
          else
            echo "No air data file exists"
          fi
          echo -e "\n파일 크기:"
          ls -lh data/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
