name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread google-auth
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Fetch Trucking Data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: |
          python scripts/fetch_truck_data.py
          echo "생성된 파일:"
          ls -la data/
          echo -e "\nJSON 내용 샘플:"
          jq '.["TN"]' data/data.json || echo "JSON 파싱 실패"

      - name: Verify Rail Data
        run: |
          echo "Rail data validation:"
          python -c "
          import json
          try:
            with open('data/us-rail.json', 'r') as f:
              data = json.load(f)
              print(f'✅ 유효한 JSON 데이터 (총 {len(data)}개 항목)')
              print('샘플 데이터:')
              print(json.dumps(data[0], indent=2))
          except Exception as e:
            print(f'❌ JSON 검증 실패: {str(e)}')
            exit(1)
          "

      - name: Fetch Rail Data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: |
          python scripts/fetch_rail_data.py
          echo "Rail data file:"
          ls -la data/us-rail.json || echo "Rail data file not found"
          echo -e "\nRail data sample:"
          if [ -f "data/us-rail.json" ]; then
            jq '.[0]' data/us-rail.json
          else
            echo "No rail data file exists"
          fi

      - name: Verify JSON files
        run: |
          echo "Trucking data sample:"
          jq -r '.["TN"]' data/data.json
          echo -e "\nRail data sample:"
          jq -r '.[0]' data/us-rail.json
          echo -e "\n파일 크기:"
          ls -lh data/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
