name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread google-auth
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Fetch Google Sheets data
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIAL_JSON: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
        run: |
          python scripts/fetch_data.py
          ls -la data/  # 파일 생성 확인
          cat data/data.csv  # 내용 확인 (디버깅용)

      - name: Verify files
        run: |
          ls -R data
          cat data/data.csv | head -n 5
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
